#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
    path: /login_check
    methods: [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui